name: Basic Check
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run a quick test step
        run: echo "Hello, GitHub Actions is working!"
